language: python

sudo: false

python:
  - "3.4"

before_install:
  - npm install -g grunt-cli

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements-soft.txt
  - python setup.py install
  - npm install

services:
  - redis-server

addons:
  postgresql: "9.4"

before_script:
  - psql -U postgres -c "CREATE USER lux WITH PASSWORD 'luxtest';"
  - psql -U postgres -c "ALTER USER lux CREATEDB;"
  - psql -U postgres -c "ALTER USER lux LOGIN;"
  - psql -U postgres -c "CREATE DATABASE luxtests;"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE luxtests to lux;"

script:
  - grunt jasmine
  - flake8
  - rm -rf lux
  - python -m runtests --coverage --test-timeout 10 --log-level warning
  - python -m runtests --coveralls

# after_script:
#   - killall rethinkdb

notifications:
  email: false

# Only test master and dev
branches:
  only:
    - master
    - dev
